### PR TITLE
Create Makefile

### LINKED ISSUE #256: [FEATURE REQUEST] Update `codecheck.sh` to support pytest locally
**Is your feature request related to a problem? Please describe.**
[GitHub-supported runners only have 7 GB RAM and 14 GB SSD](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). We therefore cannot run pytest through GitHub actions for large datasets. 

**Describe the solution you'd like**
A possible solution to this problem is for large dataset contributors to run pytest locally on their own machine and then upload the pytest results together with the PR. To ease this step, we should update `codecheck.sh` (or create a new script like this) to include pytest. Ideally, this script should mimic the current pytest workflow and create a result file when the dataset contributor run it locally. The contributor will then upload the pytest result file online and attach the link to it in the PR. 

Perhaps we can also open a public Google Group so the dataset contributors can email the pytest result files to the group.

**Additional context**

GitHub-supported runners:

### PR DESCRIPTION
**Pull request by xingjian-zhang**
Create a Makefile for GLI project.

## Description

The Makefile contains following commands:
```
Usage: make <command>
 Available commands:
  setup:    install the full project.
  clean:    remove all data files (npz).
  test:     run all tests (pystyle, pylint, pytest). Stop on failure.
   pystyle:  run pycodestyle and pydocstyle tests.
   pylint:   run pylint.
   pytest:   run pytests with all tests.
  donwload: download and preprocess all data files (npz).
```
*This message will show up by typing `make` or `make help`.

## Related Issue

#256

## Motivation and Context

This Makefile will simplify the workflow of contributors and maintainers.

## How Has This Been Tested?

Tested on my own machine on each command.

### CODE REVIEW

**Review by jiaqima — COMMENTED** [review]
I'm not familiar with the Makefile syntax. One comment is that pytest relies on a temporary file temp/changed_datasets to determine which datasets to test. Do we need that in this case?

**Comment by xingjian-zhang** [comment]
`make pytest` will run all tests (on all datasets) by default if there is not temp/changed_datasets. https://github.com/Graph-Learning-Benchmarks/gli/blob/bae59ebb4b135b47925bd5109309655e8cefb30f/tests/utils.py#L79-L89

Is that an okay behavior? We can add more sub-command if needed.

**Comment by jiaqima** [comment]
> `make pytest` will run all tests (on all datasets) by default if there is not temp/changed_datasets.
> 
> Is that an okay behavior? We can add more sub-command if needed.

Yes, that behavior is expected. I was wondering whether we want to replicate the step that creates `temp/changed_datasets` as well. 

There are two use cases for a contributor to test locally. The first one is when the user makes a change in `/gli` or `/test`. In this case we would want to test on all datasets. The second one is when the user makes a change in a dataset that is too large to test online. In this case, we probably would like to test only on this dataset.

Or we can merge this PR first and open a deferred issue to implement `temp/changed_datasets` later.

**Comment by xingjian-zhang** [comment]
I see. Yes, we can merge this PR first and open an issue later.

**Pull request merged**
