### PR TITLE
Add 6 new datasets - Twitch social networks

### PR DESCRIPTION
**Pull request by tingwl0122**
Add 6 Twitch social networks from the paper:
"Multi-Scale Attributed Node Embedding"

For each dataset: "metadata.json", "preprocess.ipynb", "README.md", "task_node_classification.json" are included.

### CODE REVIEW

**Comment by jiaqima** [comment]
@tingwl0122, a couple of general comments:

1. Please remove your local IDE config files from the commit (those under .idea).
2. We are changing the data loading API a little bit (see PR #325). So please wait a couple of days for us to merge that PR and then create npz files following the new format.

**Comment by jiaqima** [comment]
@StevenGolden1203, could you check why all the tests are skipped in this PR?

**Comment by tingwl0122** [comment]
> @StevenGolden1203, could you check why all the tests are skipped in this PR? Possibly a bug introduced by PR #329?

I have removed the unnecessary files.
Sure, I'll run tags locally first.

**Comment by tingwl0122** [comment]
> I have removed the unnecessary files. Sure, I'll run tags locally first.

**Comment by jiaqima** [comment]
BTW, please also avoid the previous commit history in new PRs. 

Probably the easiest way for you to do it now is to delete your current fork and create a new fork from the latest main repo. And then add the changes and open a new PR.

**Comment by StevenGolden1203** [comment]
> @StevenGolden1203, could you check why all the tests are skipped in this PR? Possibly a bug introduced by PR #329?

I have identified the problem, an up-coming PR will fix it.

**Comment by StevenGolden1203** [comment]
@tingwl0122 Since https://github.com/Graph-Learning-Benchmarks/gli/pull/334 is merged, you can sync and check that whether the tests are running. Please let me know if there are any problems!

**Comment by tingwl0122** [comment]
> BTW, please also avoid the previous commit history in new PRs.
> 
> Probably the easiest way for you to do it now is to delete your current fork and create a new fork from the latest main repo. And then add the changes and open a new PR.

Sure, I'll do that!

**Comment by tingwl0122** [comment]
> @tingwl0122 Since #334 is merged, you can sync and check that whether the tests are running. Please let me know if there are any problems!

No problem!

**Pull request closed without merging**
