### PR TITLE
Add models for graph classification

### PR DESCRIPTION
**Pull request by StevenGolden1203**
Add GIN model for graph classification.

A related issue will be raised. The labels of current dataloader seems problematic. I go around it temporarily.

## How Has This Been Tested?
Training can go smoothly.

e2a67608710eb5b57b80c8db1c2a6ef

### CODE REVIEW

**Comment by jiaqima** [comment]
Hi @StevenGolden1203, could you explicitly refer to the related issue so that we can track the progress?

**Comment by StevenGolden1203** [comment]
@jiaqima The issue mentioned is https://github.com/Graph-Learning-Benchmarks/gli/issues/271, which is already fixed. Also, I have updated the code in this PR.

**Comment by StevenGolden1203** [comment]
Now graph classification can be performed on GIN, GCN, ChebNet with ogbg-molhiv. ogbg-molpcba has a issue: https://github.com/Graph-Learning-Benchmarks/gli/issues/280

Model DGN is on the way.

**Comment by StevenGolden1203** [comment]
The DGNConv provided by dgl seems problematic. I raised a issue about this on dgl forum: https://discuss.dgl.ai/t/dgnconv-is-not-working-without-eig-vec/3192. I uploaded the current code anyway.

**Comment by StevenGolden1203** [comment]
Now training is runable on ogbg-molhiv and ogbg-molpcba

**Comment by StevenGolden1203** [comment]
@jiaqima Now training can go successfully on any combination between all graph classification datasets with all models except DGN. Maybe we can merge this PR.

**Pull request merged**
