### PR TITLE
Use safe save/load method for arrays.

### LINKED ISSUE #266: Use non-pickle save/load method
**Is your feature request related to a problem? Please describe.**
The pickle-based method is unsafe when the scipy version varies. See https://stackoverflow.com/a/72632847

**Describe the solution you'd like**
We need a new method to save and load arrays without pickling.

**Describe alternatives you've considered**
Ask the contributors to use a lower version when testing fails due to this issue.

**Additional context**
- [Save Load Scipy Sparse Csr Matrix In Portable Data Format
](https://www.faqcode4u.com/faq/456270/save-load-scipy-sparse-csr-matrix-in-portable-data-format)
- [NumPy: consequences of using 'np.save()' with 'allow_pickle=False'](https://stackoverflow.com/questions/41696360/numpy-consequences-of-using-np-save-with-allow-pickle-false)

### PR DESCRIPTION
**Pull request by xingjian-zhang**
## Description

This pull request
- Add a utility function `save_date` for users to safely save multiple arrays.
```python
from gli.utils import save_data
data = {
    "node_feats": node_feats,
    "node_class": node_class,
    "edge": edge,
    "node_list": node_list,
    "edge_list": edge_list
}
save_data("cora", **data)
```
```
Save all dense arrays to cora.npz, including ['node_class', 'edge', 'node_list', 'edge_list']
Save sparse matrix node_feats to cora_node_feats.sparse.npz
```
- Update the utility function `load_data` for gli to safely load array(s) from file.
- Update cora as an example for dataset saving and loading.

## Related Issue

#264 
Fix #266 

## Motivation and Context

See https://github.com/Graph-Learning-Benchmarks/gli/issues/266#issuecomment-1258898577

## How Has This Been Tested?

I only tested this feature on the aforementioned updated version of cora dataset. This PR will not pass unless all npz files are updated accordingly.

### CODE REVIEW

**Comment by jiaqima** [comment]
@xingjian-zhang, maybe let's update the urls.json in cora as well to test if it can pass all the tests. You can directly put the new npz files into your shared Dropbox folder. 

If the tests passed, we can merge this PR first. After we settle down the file storage solution in #302, we can open another PR to make the changes for all remaining datasets and change the urls at the same time.

**Comment by jiaqima** [comment]
@xingjian-zhang, do we want to bring some naming convention to the npz files too?

For example, do we want to have just 2 files, one for numpy arrays and another for scipy sparse arrays? 

Or do we want to have arrays used by metadata.json and task.json files stored in different files?

We do not need to enforce the naming convention for contributors when they contribute other datasets. But it might be good to make it cleaner as examples.

**Comment by xingjian-zhang** [comment]
> This is for sure. That means our loading method should not be based on the assumption that our user can always follow the naming convention. However, I think it is necessary for users to specify if an npz file contains a sparse array by the suffix `*.sparse.npz`. Otherwise, it is hard to determine whether an npz file saves multiple dense arrays or contains a sparse array.

Or maybe we can distinguish them by the format attribute in metadata.json.

**Comment by xingjian-zhang** [comment]
> @xingjian-zhang, maybe let's update the urls.json in cora as well to test if it can pass all the tests. You can directly put the new npz files into your shared Dropbox folder.
> 
> If the tests passed, we can merge this PR first. After we settle down the file storage solution in #302, we can open another PR to make the changes for all remaining datasets and change the urls at the same time.
> 
> Since we haven't fixed #225, the tests will pass once the urls.json is updated for cora.

I updated the URLs for cora. And it passed all tests but #338 locally.

**Comment by jiaqima** [comment]
> > @xingjian-zhang, maybe let's update the urls.json in cora as well to test if it can pass all the tests. You can directly put the new npz files into your shared Dropbox folder.
> > If the tests passed, we can merge this PR first. After we settle down the file storage solution in #302, we can open another PR to make the changes for all remaining datasets and change the urls at the same time.
> > Since we haven't fixed #225, the tests will pass once the urls.json is updated for cora.
> 
> I updated the URLs for cora. And it passed all tests but #338 locally.

I looked at the test error here and it looks like we either need to update  `tests/test_metadata.py` or add a dummy `key` in metadata.json. Because `key` is required in our current test. See the following four lines.

https://github.com/Graph-Learning-Benchmarks/gli/blob/0abd453c173e2a54fb63c6b3f02982b089c6ed40/tests/test_metadata.py#L43

https://github.com/Graph-Learning-Benchmarks/gli/blob/0abd453c173e2a54fb63c6b3f02982b089c6ed40/tests/test_metadata.py#L51

https://github.com/Graph-Learning-Benchmarks/gli/blob/0abd453c173e2a54fb63c6b3f02982b089c6ed40/tests/test_metadata.py#L79

https://github.com/Graph-Learning-Benchmarks/gli/blob/0abd453c173e2a54fb63c6b3f02982b089c6ed40/tests/test_metadata.py#L95

**Comment by jiaqima** [comment]
@xingjian-zhang, I fixed test_metadata.py within this PR. Feel free to merge if everything looks good.

**Pull request merged**
