### PR TITLE
Change repo name

### LINKED ISSUE #237: Change repo name to Graph Learning Indexer
**Is your feature request related to a problem? Please describe.**
https://github.com/Graph-Learning-Benchmarks/GLB-Repo/pull/231#issuecomment-1217368937

**Describe the solution you'd like**
Change the full name to **Graph Learning Indexer**, and the module name to `gli`.

### LINKED ISSUE #251: Remove `examples/`
**Is your feature request related to a problem? Please describe.**
The `examples/` dir should be deprecated.

**Describe the solution you'd like**
Remove the dir completely.

### PR DESCRIPTION
**Pull request by xingjian-zhang**
Change the name of the repo to GLI

## Description
This PR includes the following changes:

- [x] - Remove redundant examples.
- [x] - Change `glb` to `gli`, `GLB` to `GLI` in all docs.
- [x] - Change `glb` to `gli`, `GLB` to `GLI` in all code files.
- [x] - Change the url that contains `GLB-Repo` to `gli`

## Related Issue
Fixed #251 
Fixed #237 

## How Has This Been Tested?

Passed all tests locally.
image

### CODE REVIEW

**Comment by xingjian-zhang** [comment]
It seems that an error about squirrel_task.npz occurs in the testing: https://github.com/Graph-Learning-Benchmarks/gli/runs/8043233677?check_suite_focus=true#step:7:478

**Comment by xingjian-zhang** [comment]
Is this related to #252 ?

**Comment by jiaqima** [comment]
> It seems that an error about squirrel_task.npz occurs in the testing: https://github.com/Graph-Learning-Benchmarks/gli/runs/8043233677?check_suite_focus=true#step:7:478

Yes, I'm looking into it. It's possibly due to #250. I basically add a preprocess step to download all npz files from a single tar ball hosted in Dropbox (https://github.com/Graph-Learning-Benchmarks/gli/blob/82cb033eba8275620e275592c6456ca9c899168e/tests/preprocess.py#L6) to avoid the download quota limit when there are a lot of tests triggered (see #246). So it is possible that the squirrel_task.npz in the combined tar ball is corrupted, since the test passes when testing squirrel alone (#252). But the tests are passing on my local machine with the data from the tar ball.

**Comment by jiaqima** [comment]
@xingjian-zhang, could you download the data [here](https://www.dropbox.com/s/ltt1q7i7bh3cu2h/datafiles.tar?dl=0) and replace the squirrel npz files at your local machine with the data downloaded here, and see if the tests will pass?

**Review by jiaqima — APPROVED** [review]
LGTM

**Comment by jiaqima** [comment]
@xingjian-zhang, the test should be fixed by #254. [A full test by workflow_dispatch passed](https://github.com/Graph-Learning-Benchmarks/gli/actions/runs/2938056457). Not sure why the test for this PR still fails.

**Comment by xingjian-zhang** [comment]
I guess it's due to the conflicting?

**Comment by xingjian-zhang** [comment]
@jiaqima. After merging the conflicts, the pr passes all the tests.

**Pull request merged**
